### ISSUE TITLE
Bazı videolar için çeviri yapıyor ancak bazıları için yapmıyor.

### ISSUE THREAD

**Issue by mustafakurban** [mucahit-sahin/coursera-subtitle-translate-extension#3]
Sorun neyden kaynaklannıyor olabilir acaba bir fikri olan var mı?

**Comment by mucahit-sahin** [comment]
Merhaba Mustafa,
Videoların İngilizce altyazına sahip olması şart ve gün içerisinde çok kez çeviri yapıldıysa Google Translate'in sınırından kaynaklı çeviri işlemi o gün için duruyor. Bunun dışında şuan için bir fikrim yok.

İyi günler.

**Comment by mustafaozx** [comment]
> Merhaba Mustafa, Videoların İngilizce altyazına sahip olması şart ve gün içerisinde çok kez çeviri yapıldıysa Google Translate'in sınırından kaynaklı çeviri işlemi o gün için duruyor. Bunun dışında şuan için bir fikrim yok.
> 
> İyi günler.

Mücahit merhaba, problemi incelediğim zaman kullandığın api sadece 5000 karakter için translate yapıyor. Eğer video süresi uzunsa yani konuşulan kelime fazla ise çeviri yapılmıyor. XML request gönderirken "encodedUri" nin 5 bin karakterden fazla olmaması gerekiyor. Bu requesti parçalara bölerek yapararsan sorun çözülür.
